version: "3.9"

services:
  portal:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORTAL_ADDR: ":8080"
      PORTAL_REDIS_ADDR: "redis:6379"
      PORTAL_DSN: "file:/data/portal.db?_pragma=foreign_keys(ON)"
      PORTAL_CONTENT_DIR: "/portal/content"
      PORTAL_TEMPLATES_DIR: "/portal/web/templates"
      PORTAL_STATIC_DIR: "/portal/web/static"
    depends_on:
      - redis
    volumes:
      - portal-data:/data
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"

volumes:
  portal-data:
